version: '3'

services:
  php:
    container_name: php
    build: php
    volumes:
      - ../services/service:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ../services/service:/var/www
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    ports:
      - 3306:3306
    volumes:
      - ./mysql-master/var/lib/mysql:/var/lib/mysql
      - ./mysql-master/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    ports:
      - 13306:3306
    depends_on:
      - mysql-master
    tmpfs: /var/lib/mysql
    volumes:
      - ./mysql-slave/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-slave/docker-entrypoint-initdb.d/start-slave.sh:/docker-entrypoint-initdb.d/start-slave.sh
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
